server:
  port: 8081
  servlet.context-path: /luckey
limit:
  min: 0.01
  max: 10000
  desc: 最少要发${limit.min},最多${limit.max}


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/test?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true